name: anime_mt
description: Anime MT - Your Anime World

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  cached_network_image: ^3.3.0
  video_player: ^2.8.1
  chewie: ^1.5.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "icon.png"

flutter:
  uses-material-design: true